Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> fp=open('C:\\Users\\sony\\Desktop\\rosalind_subs.txt','r')
>>> str=fp.readlines()
>>> str[0]
'TTCCCGATACGAGATACGAGTAATACGAGATACGAGTATACGAGATACGAGGATATACGAGCTATACGAGATGATACGAGCAATACGAGGAAATACGAGTTTATACGAGAAATACGAGGCTATACGAGTGATACGAGAATGCCATACGAGATGTCTGGTAATACGAGATACGAGACTGGAATACGAGTTTTATACGAGCCATACGAGATTATACGAGATACGAGCTTGATTACTCCCATACGAGGATACGAGCGTCACACACAAATACGAGATACGAGGATACGAGATACGAGATACGAGTCTTTTCGCTATACGAGATACGAGGTTGAATACGAGAGATGATACGAGGGTTAGGTATGATACGAGTCATACGAGTATACGAGATATACGAGTTGGAGAGGATTTAAATACGAGAATATACGAGTCCGTATACGAGCAAGAGATCAATACGAGGACCCTAAATACGAGAGTTCAAGAATACGAGGATACGAGATACGAGGAACGATATACGAGAATACGAGATACGAGCATTTGCCCAATACGAGCCGTCATACGAGCAGAGGATACGAGCGAAGGGATACGAGAACATACGAGTGATACGAGCCGTATACGTTATACGAGCACCTAGGCGTGAAGACCTACAATACGAGATACGAGATACGAGATACGAGATACGAGATACGAGTATACGAGAATACGAGATACGAGCCATACGAGTATACGAGAAATACGAGTGTCATACGAGTATACGAGCATTATACGAGATACGAGAAGATACGAGATACGAGATACGAGAATACGAGTGCTCATACGAGATACGAGATACGAGAATACGAGCATACGAGATACGAGATACGAGTTATACGAGATACGAGGATATACGAGTAAATACGAGTCGAATACGAG\n'
>>> str[1]
'ATACGAGAT\n'
>>> str[1]=str[1].strip()
>>> for i in range(len(str[0])):
	if str[1]==str[0][i:i+len(str[1])]:
		print i

		
6
22
37
63
143
160
200
210
264
279
286
310
376
485
514
643
650
657
664
671
694
757
774
781
808
815
838
845
861
>>> 
fp=open('C:\\Users\\sony\\Desktop\\1.txt','r')
>>> str=fp.readlines()
>>> str[0]
'ACACCTGAAGGGCCTAAAAGGGCCCTGAATTTAAGGGCCTCAAAGGGCCAAGGGCCAAGGGCCACAAGGGCCCAAAGGGCCGTGCCTAGGTCCAAAGGGCCCGAAGGGCCGCATCCAAGGGCCGGAAGGGCCAAGGGCCAGCGCCAAAGGGCCAAGGGCCAAGGGCCAAGGGCCGATGTAGGAGAAAGGGCCAGGAAAAGGGCCTAAGGGCCAAGGGCCCGACCAAGGGCCAAGGGCCAAGGGCCAAGCAAGGGCCAAGGGCCGTGTGAAGGGCCTCCAAGGGCCGGCCGAAGGGCCTGAAGGGCCAGAAGGGCCATGGTATAAGGGCCTAAAGGGCCAAAGGGCCAGGTGCAAGGGCCGCTAAAGTTCTGAGCAAGGGCCAAGGGCCAGAAAGGGCCACGTACAAGGGCCAAGGGCCGTGAAGGGCCAAGAAAGGGCCTAAGGGCCGCCACAAAAGGGCCGAAGGGCCAGCGCTGCAAGGGCCTAAGGGCCCCTCTTAAGGGCCTGGAAAAAGGGCCAAGGGCCATTTAAAGGGCCATATAAGGGCCGCAAAGGGCCAGGCCATAAGGGCCGCGCAAGGGCCAAAGTCCAAGGGCCAAGGGCCAAGGGCCTCTTTTATAAGGGCCGTTGCAAGGGCCTGAAAGGGCCCGGAAGGGCCTGTCAAGGGCCTTTACAAGGGCCGAAGGGCCAAGGGCCCAAGGGCCTAAGGGCCCTAAGGGCCAAGGGCCAAAGGGCCAAGGGCCAAGGGCCAAGGGCCAAGGGCCGGCTATCAAAGGGCCGGCAAGGGCCAGTTGGGACCCGTAGTTATCGACTAAAGGGCCAGAAGGGCCGGAAGGGCCAAGGGCCTCTACGAAGGGCCGTTAAGGGCCTTTCAAGGGCC\n'
>>> str[1]
'AAGGGCCAA\n'
>>> str[1]=str[1].strip()
>>> for i in range(len(str[0])):
	if str[1]==str[0][i:i+len(str[1])]:
		print i+1

		
43
50
126
147
154
161
206
225
232
239
250
332
375
405
422
512
577
591
598
683
715
722
730
737
744
751
833
>>> 
